name: auto-publisher-dev

services:
  discord-proxy:
    extends:
      file: docker-compose.base.yml
      service: discord-proxy
    ports:
      - 8081:8080
    volumes:
      - ./services/discord-proxy/src:/home/node/app/src
      - /home/node/app/node_modules
    healthcheck:
      disable: true
    depends_on:
      rest-cache:
        condition: service_started

  bot:
    extends:
      file: docker-compose.base.yml
      service: bot
    build:
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - ./services/bot/src:/home/node/app/src
      - /home/node/app/node_modules
    depends_on:
      discord-proxy:
        condition: service_started

  rest-cache:
    extends:
      file: docker-compose.base.yml
      service: rest-cache
    ports:
      - 6379:6379

volumes:
  rest-cache-data:
