version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: .docker/Dockerfile.development
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    env_file:
      - .env.development
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    restart: unless-stopped
    command: mongod --port 27017
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
