services:
  bot:
    build:
      context: services/bot
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - rest

  rest:
    build:
      context: services/rest
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - rest-cache

  rest-cache:
    image: redis:7-alpine
    restart: unless-stopped
    command: 'redis-server --port 6379'
    volumes:
      - rest-cache-data:/data

volumes:
  rest-cache-data:
