services:
  bot:
    build:
      context: services/bot
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - rest

  rest:
    build:
      context: services/rest
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - rest-cache

  rest-cache:
    image: redis:7-alpine
    restart: unless-stopped
    command: 'redis-server --port 6379'
    volumes:
      - rest-cache-data:/data

  rest-db:
    image: mongo:6
    restart: unless-stopped
    command: mongod --port 27017
    volumes:
      - rest-db-data:/data/db

volumes:
  rest-cache-data:
  rest-db-data:
