name: auto-publisher

services:
  bot:
    extends:
      file: docker-compose.base.yml
      service: bot
    build:
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    command: npm run start
    depends_on:
      - rest

  rest:
    extends:
      file: docker-compose.base.yml
      service: rest
    build:
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/home/node/app/src
    depends_on:
      - rest-redis

  rest-redis:
    extends:
      file: docker-compose.base.yml
      service: rest-redis
    volumes:
      - rest-redis-data:/data

volumes:
  redis-data:
