name: auto-publisher

services:
  bot:
    extends:
      file: docker-compose.base.yml
      service: bot
    depends_on:
      - rest

  rest:
    extends:
      file: docker-compose.base.yml
      service: rest
    depends_on:
      - rest-cache

  rest-cache:
    extends:
      file: docker-compose.base.yml
      service: rest-cache

volumes:
  rest-cache-data:
