version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    command: yarn run start
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: 'redis-server --port 6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
