name: auto-publisher-dev

services:
  discord-proxy:
    extends:
      file: docker-compose.base.yml
      service: discord-proxy
    ports:
      - 8081:8080
    healthcheck:
      disable: true

  bot:
    extends:
      file: docker-compose.base.yml
      service: bot
    build:
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - ./services/bot/src:/home/node/app/src
      - /home/node/app/node_modules
    depends_on:
      rest:
        condition: service_started
      discord-proxy:
        condition: service_started

  rest:
    extends:
      file: docker-compose.base.yml
      service: rest
    build:
      dockerfile: .docker/Dockerfile.dev
    ports:
      - 3000:8080
    volumes:
      - ./services/rest/src:/home/node/app/src
      - /home/node/app/node_modules
    depends_on:
      rest-cache:
        condition: service_started
      rest-db:
        condition: service_started
      discord-proxy:
        condition: service_started

  rest-cache:
    extends:
      file: docker-compose.base.yml
      service: rest-cache
    ports:
      - 6379:6379

  rest-db:
    extends:
      file: docker-compose.base.yml
      service: rest-db
    ports:
      - 27017:27017

volumes:
  rest-cache-data:
  rest-db-data:
