name: auto-publisher

services:
  proxy:
    extends:
      file: docker-compose.base.yml
      service: proxy
    depends_on:
      cache:
        condition: service_started

  bot:
    extends:
      file: docker-compose.base.yml
      service: bot
    depends_on:
      proxy:
        condition: service_healthy

  cache:
    extends:
      file: docker-compose.base.yml
      service: cache

volumes:
  cache-data:
