name: auto-publisher

services:
  discord-proxy:
    extends:
      file: docker-compose.base.yml
      service: discord-proxy
    depends_on:
      rest-cache:
        condition: service_started

  bot:
    extends:
      file: docker-compose.base.yml
      service: bot
    depends_on:
      discord-proxy:
        condition: service_healthy

  rest-cache:
    extends:
      file: docker-compose.base.yml
      service: rest-cache

volumes:
  rest-cache-data:
