name: auto-publisher-dev

services:
  bot:
    extends:
      file: docker-compose.base.yml
      service: bot
    build:
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - ./services/bot/src:/home/node/app/src
      - /home/node/app/node_modules
    depends_on:
      - rest

  rest:
    extends:
      file: docker-compose.base.yml
      service: rest
    build:
      dockerfile: .docker/Dockerfile.dev
    ports:
      - 3000:8080
    volumes:
      - ./services/rest/src:/home/node/app/src
      - /home/node/app/node_modules
    depends_on:
      - rest-cache

  rest-cache:
    extends:
      file: docker-compose.base.yml
      service: rest-cache
    ports:
      - 6379:6379

volumes:
  rest-cache-data:
