version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: .docker/Dockerfile.development
    command: yarn run start:dev
    env_file:
      - .env.development
    volumes:
      - .:/app
