# Run Node.js on Alpine Linux
FROM node:20-alpine

# Define the environment variables
ENV NODE_ENV=development

# Set the working directory
WORKDIR /home/node/app

# Copy necessary files from the current directory to the working directory
COPY package.json .
COPY package-lock.json .
COPY tsconfig.json .

# Install dependencies
RUN npm install

# Start the application
CMD npm run start:dev
