# Run Node.js on Alpine Linux
FROM node:20-alpine

# Define the environment variables
ENV NODE_ENV=development

# Set the working directory
WORKDIR /home/node/app

# Copy all files from the current directory to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# Start the application in development mode
CMD npm run start:dev
